### ISSUE TITLE
Week 5 Review Ticket - Bria Gilliam

### ISSUE THREAD

**Issue by B-G101** [B-G101/B-G101.github.io#5]
Total Score: 5/5
Individual 2/2
- CB Create Task completed and documented on GH Pages - Prep to submit to CB on or before May, 2nd. 
     - [ ] CB Create Task Coding requirements documented
     - [ ] Runtime of Code(with comments) on Replit/Intellij

PBL 3/3
- Accounts and Logins Challenges/Hacks 
     - [ ] Start or add to existing project:  __init__.py, main.py, requirements.txt and cruddy blueprint directory are things you will need to add to your existing project.  Additionally, you should start with some of the content in templates and static folders.  Find a pair and work on this together.  Ask questions.
     - [ ] Analysis: the csp.nighthawkcodingsociety.com implementation is for educational purposes.  It has some obvious flaws in its security.   Discuss some of the flaws that you see in its security as implemented.
     - [ ] Hack #1 Add Phone Number to Sign Up / Authorization screen
     - [ ] Hack #2 Add logout to CRUD screen
     - [ ] Hack #3 Add login_required to another portion of the project
     - [ ] Extra Credit:  A quality design would have login and logout on Navbar with user information.   Be sure to have login protecting something on your site, however, do NOT make entire site under login_required.

**Comment by paigemccartin** [comment]
Score: 5/5

- [x] CB Create Task completed and documented on GH Pages - Prep to submit to CB on or before May, 2nd. (2 Points - Individual) (Score: (2/2)
     - CB Create Task Coding requirements documented
     - Runtime of Code(with comments) on Replit/Intellij
Comments: Shown in GitHub pages. Running in Intellij

- [ ] Accounts and Logins Challenges/Hacks ( 3 Points - Pair/Trio)
     - Start or add to existing project:  __init__.py, main.py, requirements.txt and cruddy blueprint directory are things you will need to add to your existing project.  Additionally, you should start with some of the content in templates and static folders.  Find a pair and work on this together.  Ask questions.
     - Analysis: the csp.nighthawkcodingsociety.com implementation is for educational purposes.  It has some obvious flaws in its security.   Discuss some of the flaws that you see in its security as implemented.
     - Hack #1 Add Phone Number to Sign Up / Authorization screen
     - Hack #2 Add logout to CRUD screen
     - Hack #3 Add login_required to another portion of the project
     - Extra Credit:  A quality design would have login and logout on Navbar with user information.   Be sure to have login protecting something on your site, however, do NOT make entire site under login_required.

comment: Login works and is running. Allows user to enter login. Has a remember me check. Has a link to sign up. Crud is shown. She also made it so you can see phonenumber. Log out works.
